// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;

import edu.wpi.first.math.trajectory.Trajectory;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.CommandBase;
import edu.wpi.first.wpilibj2.command.CommandScheduler;
import frc.robot.Paths;
import frc.robot.subsystems.DrivetrainSubsystem;

/**
 *
 */
public class AutonomousCommand extends CommandBase {

    private DrivetrainSubsystem m_drivetrainSubsystem;
    private Command m_path;

    public AutonomousCommand(DrivetrainSubsystem drivetrainSubsystem) {

        m_drivetrainSubsystem = drivetrainSubsystem;
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        Trajectory m_exampleTrajectory = Paths.threeBall2;

        m_path = new FollowPath(m_drivetrainSubsystem, m_exampleTrajectory);
        CommandScheduler.getInstance().schedule(m_path.andThen(() -> {m_drivetrainSubsystem.setVoltage(0);}));


    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        m_path.cancel();
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return m_path.isFinished();
    }

    @Override
    public boolean runsWhenDisabled() {
        return false;
    }
}
