// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;

import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.DrivetrainSubsystem;

/**
 *
 */
public class DrivetrainJoystick extends CommandBase {

    private final DrivetrainSubsystem m_drivetrainSubsystem;

    private final XboxController m_driver;

    public DrivetrainJoystick(DrivetrainSubsystem subsystem, XboxController driver) {

        m_drivetrainSubsystem = subsystem;
        addRequirements(m_drivetrainSubsystem);

        m_driver = driver;
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        double xAxis = m_driver.getLeftX();
        double yAxis = m_driver.getLeftY();
        m_drivetrainSubsystem.setArcadeDrive(xAxis, yAxis);
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        return false;

    }
}
