// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;

import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.FlywheelSubsystem;

/**
 *
 */
public class RunFlywheelJoystick extends CommandBase {

    private final FlywheelSubsystem m_flywheelSubsystem;

    private XboxController m_operator;

    public RunFlywheelJoystick(FlywheelSubsystem subsystem, XboxController operator) {

        m_operator = operator;

        m_flywheelSubsystem = subsystem;
        addRequirements(m_flywheelSubsystem);
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        double axis = m_operator.getRawAxis(XboxController.Axis.kRightTrigger.value);

        if (axis >= 0.01) {
            m_flywheelSubsystem.setSpeed(axis);
        }
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        return false;
    }
}
